### ISSUE TITLE
precinct-visulization.ipynb seems corrupted

### ISSUE THREAD

**Issue by jbartonthomas** [dsummersl/nc_election_2016#1]
This notebook won't open in local jupyter or with the git ipynb renderer.

Error loading notebook
Unreadable Notebook: /Users/thomasj/nc_election_2016/precinct-visualization.ipynb NotJSONError('Notebook does not appear to be JSON: \'{\\n "cells": [\\n {\\n "cell_type": "m...',)

**Comment by dsummersl** [comment]
Ah man, sorry about that...I'll be working on this tonight @ codefordurham - I'll look into this then and get back to you.

**Comment by dsummersl** [comment]
Should be fixed!
